const graphData = {
  "nodes": [
    {"id": "Ligne THT Amiens – Petit-Caux", "label": "Ligne THT Amiens\nPetit-Caux", "group": "Projet central", "size": 30, "detail": "Projet de ligne électrique 400 kV entre Petit-Caux et Amiens, porté par RTE."}, 
    {"id": "Forêt d’Eu", "label": "Forêt d’Eu", "group": "Projet central", "size": 24, "detail": "Espace forestier traversé par le tracé contesté ; au cœur des griefs sur la déforestation et la biodiversité."}, 
    {"id": "Petit-Caux", "label": "Petit-Caux", "group": "Projet central", "size": 15, "detail": "Point d’arrivée / zone structurante du projet côté Seine-Maritime."}, 
    {"id": "Amiens", "label": "Amiens", "group": "Projet central", "size": 15, "detail": "Point de connexion / zone structurante du projet côté Somme."}, 
    {"id": "EPR2 de Penly", "label": "EPR2 de Penly", "group": "Projet central", "size": 15, "detail": "Élément de justification énergétique du projet, avec les futurs besoins de raccordement et de sécurisation du réseau."}, 
    {"id": "Stop THT 76-80", "label": "Stop THT 76-80", "group": "Noyau d’opposition local", "size": 24, "detail": "Association / collectif principal opposé au projet ; mobilisations, communication et recours juridiques envisagés."}, 
    {"id": "Associations nationales de défense de l’environnement", "label": "Associations nationales de défense de l’environnement", "group": "Noyau d’opposition local", "size": 15, "detail": "Soutien annoncé à Stop THT 76-80, mais aucune organisation nationale n’est nommément identifiée dans le corpus."}, 
    {"id": "Sylvain Finet", "label": "Sylvain Finet", "group": "Opposants / critiques nommément cités", "size": 24, "detail": "Président de Stop THT 76-80 ; conteste la justification énergétique du projet, ses impacts environnementaux et annonce des recours juridiques."}, 
    {"id": "Francine Adam", "label": "Francine Adam", "group": "Opposants / critiques nommément cités", "size": 18, "detail": "Riveraine de Touffreville-sur-Eu ; opposée au passage de la ligne près de son habitation, évoque la perte de valeur immobilière et l’abattage d’arbres."}, 
    {"id": "José Adam", "label": "José Adam", "group": "Opposants / critiques nommément cités", "size": 18, "detail": "Riverain de Touffreville-sur-Eu ; opposé au projet, refuse la ligne de manière ferme."}, 
    {"id": "Mathieu Massy", "label": "Mathieu Massy", "group": "Opposants / critiques nommément cités", "size": 18, "detail": "Agriculteur opposé au projet sur son exploitation ; refuse les implantations de pylônes sur ses terres."}, 
    {"id": "Reynald Massy", "label": "Reynald Massy", "group": "Opposants / critiques nommément cités", "size": 18, "detail": "Éleveur opposé au projet ; craint les impacts sur l’élevage et la suppression d’un bosquet protecteur."}, 
    {"id": "Christine Rodier", "label": "Christine Rodier", "group": "Opposants / critiques nommément cités", "size": 24, "detail": "Maire de Millebosc ; opposée au tracé traversant la forêt d’Eu et critique la destruction de forêt."}, 
    {"id": "Rollon Mouchel-Blaisot", "label": "Rollon Mouchel-Blaisot", "group": "Élus / acteurs institutionnels", "size": 18, "detail": "Préfet de la Somme ; position institutionnelle prudente, reconnaît les nuisances mais défend une nécessité nationale."}, 
    {"id": "Emmanuel Moulard", "label": "Emmanuel Moulard", "group": "Élus / acteurs institutionnels", "size": 15, "detail": "Secrétaire général de la préfecture de la Somme ; présente les dispositifs d’accompagnement et d’indemnisation."}, 
    {"id": "Maire de Touffreville-sur-Eu", "label": "Maire de Touffreville-sur-Eu", "group": "Élus / acteurs institutionnels", "size": 15, "detail": "Maire non nommé ; cité lors de visites de RTE, sans position exprimée dans le corpus."}, 
    {"id": "FDSEA 80", "label": "FDSEA 80", "group": "Organisations agricoles / foncières", "size": 15, "detail": "Syndicat agricole défendant les agriculteurs concernés ; demande une meilleure indemnisation sans opposition explicite au projet."}, 
    {"id": "FDSEA Seine-Maritime", "label": "FDSEA Seine-Maritime", "group": "Organisations agricoles / foncières", "size": 15, "detail": "Syndicat agricole impliqué dans les négociations avec RTE sur les compensations."}, 
    {"id": "JA 80", "label": "JA 80", "group": "Organisations agricoles / foncières", "size": 15, "detail": "Jeunes Agriculteurs Somme ; contestent les compensations proposées."}, 
    {"id": "FNSEA 76", "label": "FNSEA 76", "group": "Organisations agricoles / foncières", "size": 15, "detail": "Organisation agricole revendiquant une meilleure prise en compte des préjudices."}, 
    {"id": "Chambre d’agriculture de la Somme", "label": "Chambre d’agriculture de la Somme", "group": "Organisations agricoles / foncières", "size": 15, "detail": "Institution agricole partie prenante des discussions et de la défense des intérêts agricoles."}, 
    {"id": "Propriétaires ruraux / PPR", "label": "Propriétaires ruraux\nPPR", "group": "Organisations agricoles / foncières", "size": 15, "detail": "Organisation foncière représentant les propriétaires ruraux associés aux négociations."}, 
    {"id": "CGB 80", "label": "CGB 80", "group": "Organisations agricoles / foncières", "size": 15, "detail": "Syndicat betteravier intervenant sur les impacts logistiques et les contraintes d’exploitation."}, 
    {"id": "RTE", "label": "RTE", "group": "Porteurs / institutions du projet", "size": 24, "detail": "Gestionnaire du réseau de transport d’électricité ; porteur principal du projet, jugé indispensable à la transition énergétique et à la sécurité du réseau."}, 
    {"id": "Enedis", "label": "Enedis", "group": "Porteurs / institutions du projet", "size": 15, "detail": "Gestionnaire de réseau de distribution ; co-porteur de certaines infrastructures associées."}, 
    {"id": "EDF", "label": "EDF", "group": "Porteurs / institutions du projet", "size": 15, "detail": "Groupe énergétique et maison mère de RTE mentionnée dans la presse ; pas de position propre exprimée."}, 
    {"id": "Préfecture de la Somme", "label": "Préfecture de la Somme", "group": "Porteurs / institutions du projet", "size": 15, "detail": "État ; pilotage administratif et indemnitaire du dossier."}, 
    {"id": "Préfecture de Seine-Maritime", "label": "Préfecture de Seine-Maritime", "group": "Porteurs / institutions du projet", "size": 15, "detail": "État ; procédures administratives liées au projet."}, 
    {"id": "Autorité environnementale", "label": "Autorité environnementale", "group": "Porteurs / institutions du projet", "size": 15, "detail": "Autorité administrative chargée de l’avis environnemental."}, 
    {"id": "Commission indépendante d’indemnisation", "label": "Commission indépendante d’indemnisation", "group": "Porteurs / institutions du projet", "size": 15, "detail": "Instance administrative chargée d’évaluer les préjudices fonciers."}, 
    {"id": "CNDP", "label": "CNDP", "group": "Porteurs / institutions du projet", "size": 15, "detail": "Commission nationale du débat public ; organisation de la concertation publique."}, 
    {"id": "Commission d’enquête publique", "label": "Commission d’enquête publique", "group": "Porteurs / institutions du projet", "size": 15, "detail": "Instance administrative chargée de recueillir les avis du public."}, 
    {"id": "Cyril Wagner", "label": "Cyril Wagner", "group": "Porte-parole / entreprises associées", "size": 18, "detail": "Directeur adjoint ingénierie RTE Hauts-de-France ; défend le caractère absolument indispensable du projet."}, 
    {"id": "Eiffage", "label": "Eiffage", "group": "Porte-parole / entreprises associées", "size": 15, "detail": "Entreprise de travaux mentionnée par des opposants dans le cadre des travaux ; rôle précis non documenté."}, 
    {"id": "Déforestation et biodiversité", "label": "Déforestation et biodiversité", "group": "Points de vigilance / griefs", "size": 17, "detail": "Destruction annoncée de plusieurs hectares de forêt d’Eu, coupe d’arbres centenaires et atteinte aux espaces naturels."}, 
    {"id": "Busard cendré", "label": "Busard cendré", "group": "Points de vigilance / griefs", "size": 17, "detail": "Espèce protégée citée dans les inquiétudes environnementales ; les risques sont contestés par RTE selon le corpus."}, 
    {"id": "Artificialisation et paysage", "label": "Artificialisation et paysage", "group": "Points de vigilance / griefs", "size": 17, "detail": "Implantation de pylônes de grande hauteur dans des secteurs ruraux et forestiers."}, 
    {"id": "Cadre de vie", "label": "Cadre de vie", "group": "Points de vigilance / griefs", "size": 17, "detail": "Nuisances visuelles, proximité des habitations et dégradation perçue de la qualité de vie."}, 
    {"id": "Dévalorisation immobilière", "label": "Dévalorisation immobilière", "group": "Points de vigilance / griefs", "size": 17, "detail": "Crainte de perte de valeur des maisons riveraines."}, 
    {"id": "Impacts agricoles", "label": "Impacts agricoles", "group": "Points de vigilance / griefs", "size": 17, "detail": "Contraintes de circulation, projets futurs limités, perte de productivité et atteintes aux exploitations."}, 
    {"id": "Perte de chance économique", "label": "Perte de chance économique", "group": "Points de vigilance / griefs", "size": 17, "detail": "Argument porté par les organisations agricoles autour des projets empêchés ou dégradés."}, 
    {"id": "Insuffisance des indemnisations", "label": "Insuffisance des indemnisations", "group": "Points de vigilance / griefs", "size": 17, "detail": "Contestation forte des montants proposés par RTE."}, 
    {"id": "Justification énergétique contestée", "label": "Justification énergétique contestée", "group": "Points de vigilance / griefs", "size": 17, "detail": "Certains opposants estiment que les besoins avancés par RTE ne sont pas démontrés."}, 
    {"id": "Concertation jugée insuffisante", "label": "Concertation jugée insuffisante", "group": "Points de vigilance / griefs", "size": 17, "detail": "Critique sur les alternatives étudiées et le processus de décision."}, 
    {"id": "Sacrifice territorial", "label": "Sacrifice territorial", "group": "Points de vigilance / griefs", "size": 17, "detail": "Sentiment que les territoires traversés supportent les nuisances sans bénéfices directs."}, 
    {"id": "ICI Normandie / Radio France", "label": "ICI Normandie\nRadio France", "group": "Médias / sources cités", "size": 15, "detail": "Média public régional ; information générale et interviews."}, 
    {"id": "Le Parisien", "label": "Le Parisien", "group": "Médias / sources cités", "size": 15, "detail": "Quotidien national ; reportage sur la contestation."}, 
    {"id": "Actu.fr", "label": "Actu.fr", "group": "Médias / sources cités", "size": 15, "detail": "Média local ; témoignages de riverains."}, 
    {"id": "Courrier Picard", "label": "Courrier Picard", "group": "Médias / sources cités", "size": 15, "detail": "Quotidien régional ; couverture des enjeux agricoles."}, 
    {"id": "Action Agricole Picarde", "label": "Action Agricole Picarde", "group": "Médias / sources cités", "size": 15, "detail": "Presse professionnelle agricole ; suivi des négociations agricoles."}, 
    {"id": "Google News", "label": "Google News", "group": "Médias / sources cités", "size": 15, "detail": "Agrégateur ; reprise d’articles."}, 
    {"id": "RTE France", "label": "RTE France", "group": "Médias / sources cités", "size": 15, "detail": "Source institutionnelle ; présentation du projet."}, 
    {"id": "CNDP source", "label": "CNDP source", "group": "Médias / sources cités", "size": 15, "detail": "Source institutionnelle ; concertation publique."}, 
    {"id": "Curebot", "label": "Curebot", "group": "Médias / sources cités", "size": 15, "detail": "Agrégateur documentaire ; compilation des sources."}, 
    {"id": "Parcs éoliens", "label": "Parcs éoliens", "group": "Projet central", "size": 15, "detail": "Nouveaux parcs dont le raccordement justifie le projet THT selon RTE."}
  ], 
  "links": [
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Forêt d’Eu", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Petit-Caux", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Amiens", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "EPR2 de Penly", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Stop THT 76-80", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Associations nationales de défense de l’environnement", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Sylvain Finet", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Francine Adam", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "José Adam", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Mathieu Massy", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Reynald Massy", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Christine Rodier", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Rollon Mouchel-Blaisot", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Emmanuel Moulard", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Maire de Touffreville-sur-Eu", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "FDSEA 80", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "FDSEA Seine-Maritime", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "JA 80", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "FNSEA 76", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Chambre d’agriculture de la Somme", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Propriétaires ruraux / PPR", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "CGB 80", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "RTE", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Enedis", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "EDF", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Préfecture de la Somme", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Préfecture de Seine-Maritime", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Autorité environnementale", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Commission indépendante d’indemnisation", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "CNDP", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Commission d’enquête publique", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Cyril Wagner", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Eiffage", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Déforestation et biodiversité", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Busard cendré", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Artificialisation et paysage", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Cadre de vie", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Dévalorisation immobilière", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Impacts agricoles", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Perte de chance économique", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Insuffisance des indemnisations", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Justification énergétique contestée", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Concertation jugée insuffisante", "kind": "rôle"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Sacrifice territorial", "kind": "rôle"}, 
    {"source": "Stop THT 76-80", "target": "Sylvain Finet", "kind": "lien"}, 
    {"source": "Stop THT 76-80", "target": "Associations nationales de défense de l’environnement", "kind": "lien"}, 
    {"source": "Stop THT 76-80", "target": "Christine Rodier", "kind": "lien"}, 
    {"source": "Christine Rodier", "target": "Forêt d’Eu", "kind": "lien"}, 
    {"source": "Francine Adam", "target": "Cadre de vie", "kind": "lien"}, 
    {"source": "Francine Adam", "target": "Dévalorisation immobilière", "kind": "lien"}, 
    {"source": "José Adam", "target": "Cadre de vie", "kind": "lien"}, 
    {"source": "Mathieu Massy", "target": "Impacts agricoles", "kind": "lien"}, 
    {"source": "Reynald Massy", "target": "Impacts agricoles", "kind": "lien"}, 
    {"source": "FDSEA 80", "target": "Insuffisance des indemnisations", "kind": "lien"}, 
    {"source": "JA 80", "target": "Insuffisance des indemnisations", "kind": "lien"}, 
    {"source": "FNSEA 76", "target": "Insuffisance des indemnisations", "kind": "lien"}, 
    {"source": "Chambre d’agriculture de la Somme", "target": "Impacts agricoles", "kind": "lien"}, 
    {"source": "Propriétaires ruraux / PPR", "target": "Perte de chance économique", "kind": "lien"}, 
    {"source": "CGB 80", "target": "Impacts agricoles", "kind": "lien"}, 
    {"source": "RTE", "target": "Cyril Wagner", "kind": "lien"}, 
    {"source": "RTE", "target": "Enedis", "kind": "lien"}, 
    {"source": "RTE", "target": "EPR2 de Penly", "kind": "lien"}, 
    {"source": "RTE", "target": "Justification énergétique contestée", "kind": "lien"}, 
    {"source": "RTE", "target": "Commission indépendante d’indemnisation", "kind": "lien"}, 
    {"source": "RTE", "target": "CNDP", "kind": "lien"}, 
    {"source": "Préfecture de la Somme", "target": "Rollon Mouchel-Blaisot", "kind": "lien"}, 
    {"source": "Préfecture de la Somme", "target": "Emmanuel Moulard", "kind": "lien"}, 
    {"source": "Préfecture de Seine-Maritime", "target": "Commission d’enquête publique", "kind": "lien"}, 
    {"source": "Autorité environnementale", "target": "Déforestation et biodiversité", "kind": "lien"}, 
    {"source": "Busard cendré", "target": "Déforestation et biodiversité", "kind": "lien"}, 
    {"source": "Forêt d’Eu", "target": "Déforestation et biodiversité", "kind": "lien"}, 
    {"source": "Forêt d’Eu", "target": "Artificialisation et paysage", "kind": "lien"}, 
    {"source": "CNDP", "target": "Concertation jugée insuffisante", "kind": "lien"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "ICI Normandie / Radio France", "kind": "source"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Le Parisien", "kind": "source"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Actu.fr", "kind": "source"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Courrier Picard", "kind": "source"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Action Agricole Picarde", "kind": "source"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Google News", "kind": "source"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "RTE France", "kind": "source"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "CNDP source", "kind": "source"}, 
    {"source": "Ligne THT Amiens – Petit-Caux", "target": "Curebot", "kind": "source"}, 
    {"source": "RTE", "target": "Parcs éoliens", "kind": "lien"},
    {"source": "EDF", "target": "RTE", "kind": "lien"},
    {"source": "Reynald Massy", "target": "Eiffage", "kind": "lien"},
    {"source": "Sylvain Finet", "target": "RTE", "kind": "lien"}
  ]
};
